In [1]:
import sys
import torch
import socket
import importlib
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

In [44]:
import pandas as pd
import numpy as np
from src.config import raw_data_dir

data_path = raw_data_dir / "sample_data.npy"
sim = np.load(data_path, allow_pickle=True)

df = pd.DataFrame(sim)

In [10]:
df.head(10)

,initial_mass,initial_z,star_age,mass,logR,logP,logRho,logT,luminosity,opacity,x_mass_fraction_H,y_mass_fraction_He,z_mass_fraction_metals,eps_nuc,eps_nuc_neu_total,eps_grav_nh,eps_grav,zone,q
0,16.5,0.02,1.124803e+07,15.672543,2.769037,2.632306,-8.726443,3.565941,56927.325018,0.001937,0.667269,0.319678,0.013054,0.042915,1.739978e-29,-0.003933,-2.621206,1.0,1.0
1,16.5,0.02,1.124803e+07,15.672543,2.769037,2.632306,-8.726443,3.565941,56927.325018,0.001937,0.667269,0.319678,0.013054,0.042915,1.739978e-29,-0.003933,-2.621206,2.0,1.0
2,16.5,0.02,1.124803e+07,15.672543,2.769037,2.632306,-8.726443,3.565941,56927.325018,0.001937,0.667269,0.319678,0.013054,0.042915,1.739978e-29,-0.003933,-2.621206,3.0,1.0
3,16.5,0.02,1.124803e+07,15.672543,2.769037,2.632306,-8.726443,3.565941,56927.325018,0.001937,0.667269,0.319678,0.013054,0.042915,1.739978e-29,-0.003933,-2.621205,4.0,1.0
4,16.5,0.02,1.124803e+07,15.672543,2.769037,2.632306,-8.726443,3.565941,56927.325018,0.001937,0.667269,0.319678,0.013054,0.042915,1.739978e-29,-0.003933,-2.621205,5.0,1.0
5,16.5,0.02,1.124803e+07,15.672543,2.769037,2.632307,-8.726443,3.565941,56927.325018,0.001937,0.667269,0.319678,0.013054,0.042915,1.739978e-29,-0.003933,-2.621203,6.0,1.0
6,16.5,0.02,1.124803e+07,15.672543,2.769037,2.632307,-8.726443,3.565941,56927.325018,0.001937,0.667269,0.319678,0.013054,0.042915,1.739978e-29,-0.003933,-2.621202,7.0,1.0
7,16.5,0.02,1.124803e+07,15.672543,2.769037,2.632307,-8.726442,3.565941,56927.325018,0.001937,0.667269,0.319678,0.013054,0.042915,1.739979e-29,-0.003933,-2.621199,8.0,1.0
8,16.5,0.02,1.124803e+07,15.672543,2.769037,2.632307,-8.726442,3.565941,56927.325018,0.001937,0.667269,0.319678,0.013054,0.042915,1.739979e-29,-0.003933,-2.621196,9.0,1.0
9,16.5,0.02,1.124803e+07,15.672543,2.769037,2.632308,-8.726442,3.565941,56927.325018,0.001937,0.667269,0.319678,0.013054,0.042915,1.739980e-29,-0.003933,-2.621193,10.0,1.0

In [45]:
importlib.reload(sys.modules["src.preprocessing"])
from src.preprocessing import check_missing_values, drop_constant_columns, fit_preprocess_scalers

print(check_missing_values(df))

df_reduced = drop_constant_columns(df)

df_scaled, scalers = fit_preprocess_scalers(
    df_reduced,
    normalize=True,
    standardize=False,
)

output_path = Path("data/processed/processed_data.npy")
output_path.parent.mkdir(parents=True, exist_ok=True)
np.save(output_path, df_scaled.to_numpy())

print(f"Saved processed dataset to {output_path}")

Empty DataFrame
Columns: [missing_values, null_percent]
Index: []
Dropping constant columns: ['initial_mass', 'initial_z']
Saved processed dataset to data/processed/processed_data.npy

In [43]:
df_scaled.head(10)

,star_age,mass,logR,logP,logRho,logT,luminosity,opacity,x_mass_fraction_H,y_mass_fraction_He,z_mass_fraction_metals,eps_nuc,eps_nuc_neu_total,eps_grav_nh,eps_grav,zone,q
0,0.930052,0.949972,0.979358,0.065433,0.143207,0.003962,0.572842,0.000007,0.928648,0.32379,0.000348,5.971173e-08,4.132018e-34,0.40641,0.605472,0.000000,1.0
1,0.930052,0.949972,0.979358,0.065433,0.143207,0.003962,0.572842,0.000007,0.928648,0.32379,0.000348,5.971173e-08,4.132018e-34,0.40641,0.605472,0.000299,1.0
2,0.930052,0.949972,0.979358,0.065433,0.143207,0.003962,0.572842,0.000007,0.928648,0.32379,0.000348,5.971173e-08,4.132018e-34,0.40641,0.605472,0.000597,1.0
3,0.930052,0.949972,0.979358,0.065433,0.143207,0.003962,0.572842,0.000007,0.928648,0.32379,0.000348,5.971173e-08,4.132018e-34,0.40641,0.605472,0.000896,1.0
4,0.930052,0.949972,0.979358,0.065433,0.143207,0.003962,0.572842,0.000007,0.928648,0.32379,0.000348,5.971173e-08,4.132018e-34,0.40641,0.605472,0.001194,1.0
5,0.930052,0.949972,0.979358,0.065433,0.143207,0.003962,0.572842,0.000007,0.928648,0.32379,0.000348,5.971173e-08,4.132019e-34,0.40641,0.605472,0.001493,1.0
6,0.930052,0.949972,0.979358,0.065433,0.143207,0.003962,0.572842,0.000007,0.928648,0.32379,0.000348,5.971173e-08,4.132020e-34,0.40641,0.605472,0.001792,1.0
7,0.930052,0.949972,0.979358,0.065433,0.143207,0.003962,0.572842,0.000007,0.928648,0.32379,0.000348,5.971173e-08,4.132021e-34,0.40641,0.605472,0.002090,1.0
8,0.930052,0.949972,0.979358,0.065433,0.143207,0.003962,0.572842,0.000007,0.928648,0.32379,0.000348,5.971173e-08,4.132022e-34,0.40641,0.605472,0.002389,1.0
9,0.930052,0.949972,0.979358,0.065433,0.143207,0.003962,0.572842,0.000007,0.928648,0.32379,0.000348,5.971173e-08,4.132024e-34,0.40641,0.605472,0.002687,1.0